[project]
name = "arfbot"
version = "0.1.0"
description = "Simple telegram footbol game bot"
requires-python = ">=3.14"
dependencies = [
    "aiogram>=3.24.0",
    "aiosqlite>=0.22.1",
    "colorama>=0.4.6",
]
